/*
*    The contents of this file are subject to the Mozilla Public License
*    Version 1.1 (the "License"); you may not use this file except in
*    compliance with the License. You may obtain a copy of the License at
*    http://www.mozilla.org/MPL/
*    
*    Software distributed under the License is distributed on an "AS IS"
*    basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
*    License for the specific language governing rights and limitations
*    under the License.
*    
*    The Original Code is Phoenix.
*    The Initial Developers of the Original Code are Jyrno42 and 13th.
*/

#define LANG_WELCOME_TO				"Tere Tulemast %s-%sr%s-%s, Palun oota..."
#define LANG_FAILED_TO_CONNECT			"\t\t* %s - Failed to connect to mysql DB."
#define LANG_CONNECTED				"\t\t* %s - Connected to mysql DB."
#define LANG_LOADED				"\t\t* %s-%sr%s-%s Loaded."
#define LANG_UNLOADED				"\t\t* %s-%sr%s-%s UnLoaded."
#define LANG_NOCHARACTER			"Sellise nimega karakterit ei ole!"
#define LANG_NOUSER				"Sellise nimega kasutajat ei ole!"
#define LANG_DIALOG_LOGIN_CAPTION		"Palun logige sisse!"
#define LANG_DIALOG_LOGIN_INFO			"Tere, %s.\n Sisesta parool:"
#define LANG_DIALOG_LOGIN_LOGINBUTTON		"Logi Sisse!"
#define LANG_DIALOG_LOGIN_EXITBUTTON		"Välju"
#define LANG_LOGGED_IN                "Edukalt sisse logitud."
#define LANG_WRONG_PASSWORD               "Vale parool!"
#define LANG_MUST_LOGIN               "Mängimiseks pead sisse logima!"